[
  {
    mainFolder: "About",
    subFolders: [
      {
        subFolder: "Cover Photographs",
        subSubFolders: [
          {
            subSubFolder: "Cover Photographs",
            files: [
              "assets/photos/About/Cover Photographs/CP-01.JPG",
              "assets/photos/About/Cover Photographs/CP-02.JPG",
              "assets/photos/About/Cover Photographs/CP-03.JPG",
              "assets/photos/About/Cover Photographs/CP-04.jpg",
              "assets/photos/About/Cover Photographs/CP-05.JPG",
              "assets/photos/About/Cover Photographs/CP-06.jpg",
              "assets/photos/About/Cover Photographs/CP-07.JPG",
              "assets/photos/About/Cover Photographs/CP-08.JPG",
              "assets/photos/About/Cover Photographs/CP-09.jpg",
              "assets/photos/About/Cover Photographs/CP-10.JPG",
              "assets/photos/About/Cover Photographs/CP-11.JPG",
              "assets/photos/About/Cover Photographs/CP-12.JPG",
            ],
          },
        ],
      },
    ],
  },
  {
    mainFolder: "Art Photography",
    subFolders: [
      {
        subFolder: "Art Photographs",
        subSubFolders: [
          {
            subSubFolder: "Art Photographs",
            files: [
              "assets/photos/Art Photography/Art Photographs/AP-01.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-02.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-03.jpg",
              "assets/photos/Art Photography/Art Photographs/AP-04.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-05.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-06.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-07.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-08.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-09.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-10.jpg",
              "assets/photos/Art Photography/Art Photographs/AP-11.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-12.jpg",
              "assets/photos/Art Photography/Art Photographs/AP-13.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-14.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-15.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-16.jpg",
              "assets/photos/Art Photography/Art Photographs/AP-17.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-18.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-19.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-20.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-21.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-22.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-23.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-24.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-25.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-26.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-27.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-28.jpg",
              "assets/photos/Art Photography/Art Photographs/AP-29.jpg",
              "assets/photos/Art Photography/Art Photographs/AP-30.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-31.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-32.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-33.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-34.jpg",
              "assets/photos/Art Photography/Art Photographs/AP-35.jpg",
              "assets/photos/Art Photography/Art Photographs/AP-36.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-37.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-38.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-39.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-40.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-41.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-42.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-43.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-44.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-45.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-46.JPG",
              "assets/photos/Art Photography/Art Photographs/AP-47.JPG",
            ],
          },
        ],
      },
      {
        subFolder: "Photo Story-(AAGOMONI-The Advent)",
        subSubFolders: [
          {
            subSubFolder: "Photo Story-(AAGOMONI-The Advent)",
            files: [
              "assets/photos/Art Photography/Photo Story-(AAGOMONI-The Advent)/PS-01.JPG",
              "assets/photos/Art Photography/Photo Story-(AAGOMONI-The Advent)/PS-02.JPG",
              "assets/photos/Art Photography/Photo Story-(AAGOMONI-The Advent)/PS-03.JPG",
              "assets/photos/Art Photography/Photo Story-(AAGOMONI-The Advent)/PS-04.JPG",
              "assets/photos/Art Photography/Photo Story-(AAGOMONI-The Advent)/PS-05.JPG",
              "assets/photos/Art Photography/Photo Story-(AAGOMONI-The Advent)/PS-06.JPG",
              "assets/photos/Art Photography/Photo Story-(AAGOMONI-The Advent)/PS-07.JPG",
              "assets/photos/Art Photography/Photo Story-(AAGOMONI-The Advent)/PS-08.JPG",
              "assets/photos/Art Photography/Photo Story-(AAGOMONI-The Advent)/PS-09.JPG",
              "assets/photos/Art Photography/Photo Story-(AAGOMONI-The Advent)/PS-10.JPG",
              "assets/photos/Art Photography/Photo Story-(AAGOMONI-The Advent)/PS-11.JPG",
              "assets/photos/Art Photography/Photo Story-(AAGOMONI-The Advent)/PS-12.JPG",
              "assets/photos/Art Photography/Photo Story-(AAGOMONI-The Advent)/PS-13.JPG",
              "assets/photos/Art Photography/Photo Story-(AAGOMONI-The Advent)/PS-14.JPG",
              "assets/photos/Art Photography/Photo Story-(AAGOMONI-The Advent)/PS-15.JPG",
              "assets/photos/Art Photography/Photo Story-(AAGOMONI-The Advent)/PS-16.JPG",
              "assets/photos/Art Photography/Photo Story-(AAGOMONI-The Advent)/PS-17.JPG",
              "assets/photos/Art Photography/Photo Story-(AAGOMONI-The Advent)/PS-18.JPG",
              "assets/photos/Art Photography/Photo Story-(AAGOMONI-The Advent)/PS-19.JPG",
              "assets/photos/Art Photography/Photo Story-(AAGOMONI-The Advent)/PS-20.JPG",
              "assets/photos/Art Photography/Photo Story-(AAGOMONI-The Advent)/PS-21.JPG",
              "assets/photos/Art Photography/Photo Story-(AAGOMONI-The Advent)/PS-22.JPG",
              "assets/photos/Art Photography/Photo Story-(AAGOMONI-The Advent)/PS-23.JPG",
              "assets/photos/Art Photography/Photo Story-(AAGOMONI-The Advent)/PS-24.JPG",
              "assets/photos/Art Photography/Photo Story-(AAGOMONI-The Advent)/PS-25.JPG",
              "assets/photos/Art Photography/Photo Story-(AAGOMONI-The Advent)/PS-26.JPG",
            ],
          },
        ],
      },
    ],
  },
  {
    mainFolder: "EXTRA-CURRICULAR ACTIVITIES",
    subFolders: [
      {
        subFolder: "Cultural Program Photographs",
        subSubFolders: [
          {
            subSubFolder: "Cultural Program Photographs",
            files: [
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/Cultural Program Photographs/OPP-01.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/Cultural Program Photographs/OPP-02.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/Cultural Program Photographs/OPP-03.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/Cultural Program Photographs/OPP-04.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/Cultural Program Photographs/OPP-05.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/Cultural Program Photographs/OPP-06.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/Cultural Program Photographs/OPP-07.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/Cultural Program Photographs/OPP-08.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/Cultural Program Photographs/OPP-09.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/Cultural Program Photographs/OPP-10.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/Cultural Program Photographs/OPP-11.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/Cultural Program Photographs/OPP-12.JPG",
            ],
          },
        ],
      },
      {
        subFolder: "SAUPS Program Photographs",
        subSubFolders: [
          {
            subSubFolder: "SAUPS 1st National-2017",
            files: [
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS 1st National-2017/SAUPS-1st National-01.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS 1st National-2017/SAUPS-1st National-02.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS 1st National-2017/SAUPS-1st National-03.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS 1st National-2017/SAUPS-1st National-04.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS 1st National-2017/SAUPS-1st National-05.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS 1st National-2017/SAUPS-1st National-06.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS 1st National-2017/SAUPS-1st National-07.jpg",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS 1st National-2017/SAUPS-1st National-08.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS 1st National-2017/SAUPS-1st National-09.jpg",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS 1st National-2017/SAUPS-1st National-10.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS 1st National-2017/SAUPS-1st National-11.jpg",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS 1st National-2017/SAUPS-1st National-12.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS 1st National-2017/SAUPS-1st National-13.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS 1st National-2017/SAUPS-1st National-14.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS 1st National-2017/SAUPS-1st National-15.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS 1st National-2017/SAUPS-1st National-16.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS 1st National-2017/SAUPS-1st National-17.jpg",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS 1st National-2017/SAUPS-1st National-18.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS 1st National-2017/SAUPS-1st National-19.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS 1st National-2017/SAUPS-1st National-20.JPG",
            ],
          },
          {
            subSubFolder: "SAUPS- ART OF LIGHT-2nd National-2019",
            files: [
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS- ART OF LIGHT-2nd National-2019/SAUPS-2nd National-01.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS- ART OF LIGHT-2nd National-2019/SAUPS-2nd National-02.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS- ART OF LIGHT-2nd National-2019/SAUPS-2nd National-03.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS- ART OF LIGHT-2nd National-2019/SAUPS-2nd National-04.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS- ART OF LIGHT-2nd National-2019/SAUPS-2nd National-05.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS- ART OF LIGHT-2nd National-2019/SAUPS-2nd National-06.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS- ART OF LIGHT-2nd National-2019/SAUPS-2nd National-07.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS- ART OF LIGHT-2nd National-2019/SAUPS-2nd National-08.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS- ART OF LIGHT-2nd National-2019/SAUPS-2nd National-09.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS- ART OF LIGHT-2nd National-2019/SAUPS-2nd National-10.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS- ART OF LIGHT-2nd National-2019/SAUPS-2nd National-11.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS- ART OF LIGHT-2nd National-2019/SAUPS-2nd National-12.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS- ART OF LIGHT-2nd National-2019/SAUPS-2nd National-13.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS- ART OF LIGHT-2nd National-2019/SAUPS-2nd National-14.jpg",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/SAUPS- ART OF LIGHT-2nd National-2019/SAUPS-2nd National-15.JPG",
            ],
          },
          {
            subSubFolder: "Set Out-1",
            files: [
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/Set Out-1/Set Out-1-01.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/Set Out-1/Set Out-1-02.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/Set Out-1/Set Out-1-03.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/Set Out-1/Set Out-1-04.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/Set Out-1/Set Out-1-05.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/Set Out-1/Set Out-1-06.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/Set Out-1/Set Out-1-07.JPG",
            ],
          },
          {
            subSubFolder: "Shadow on the Colors",
            files: [
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/Shadow on the Colors/Shadow on the Colors-01.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/Shadow on the Colors/Shadow on the Colors-02.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/Shadow on the Colors/Shadow on the Colors-03.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/Shadow on the Colors/Shadow on the Colors-04.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/Shadow on the Colors/Shadow on the Colors-05.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/Shadow on the Colors/Shadow on the Colors-06.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/Shadow on the Colors/Shadow on the Colors-07.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/Shadow on the Colors/Shadow on the Colors-08.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/Shadow on the Colors/Shadow on the Colors-09.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/Shadow on the Colors/Shadow on the Colors-10.JPG",
              "assets/photos/EXTRA-CURRICULAR ACTIVITIES/SAUPS Program Photographs/Shadow on the Colors/Shadow on the Colors-11.JPG",
            ],
          },
        ],
      },
    ],
  },
  {
    mainFolder: "Gallary",
    subFolders: [
      {
        subFolder: "Conference Photographs",
        subSubFolders: [
          {
            subSubFolder: "Conference Photographs",
            files: [
              "assets/photos/Gallary/Conference Photographs/Conf.P-01.JPG",
              "assets/photos/Gallary/Conference Photographs/Conf.P-02.JPG",
              "assets/photos/Gallary/Conference Photographs/Conf.P-03.JPG",
              "assets/photos/Gallary/Conference Photographs/Conf.P-04.JPG",
              "assets/photos/Gallary/Conference Photographs/Conf.P-05.JPG",
            ],
          },
        ],
      },
      {
        subFolder: "Convocation Photographs",
        subSubFolders: [
          {
            subSubFolder: "Convocation Photographs",
            files: [
              "assets/photos/Gallary/Convocation Photographs/Conv.P--02.JPG",
              "assets/photos/Gallary/Convocation Photographs/Conv.P-01.JPG",
              "assets/photos/Gallary/Convocation Photographs/Conv.P-03.JPG",
              "assets/photos/Gallary/Convocation Photographs/Conv.P-04.JPG",
              "assets/photos/Gallary/Convocation Photographs/Conv.P-05.JPG",
              "assets/photos/Gallary/Convocation Photographs/Conv.P-06.JPG",
              "assets/photos/Gallary/Convocation Photographs/Conv.P-07.JPG",
              "assets/photos/Gallary/Convocation Photographs/Conv.P-08.JPG",
              "assets/photos/Gallary/Convocation Photographs/Conv.P-09.JPG",
              "assets/photos/Gallary/Convocation Photographs/Conv.P-10.JPG",
            ],
          },
        ],
      },
      {
        subFolder: "Entertainment Photographs",
        subSubFolders: [
          {
            subSubFolder: "Entertainment Photographs",
            files: [
              "assets/photos/Gallary/Entertainment Photographs/EP-01.JPG",
              "assets/photos/Gallary/Entertainment Photographs/EP-02.JPG",
              "assets/photos/Gallary/Entertainment Photographs/EP-03.JPG",
            ],
          },
        ],
      },
      {
        subFolder: "My Exhibited Art Photographs",
        subSubFolders: [
          {
            subSubFolder: "My Exhibited Art Photographs",
            files: [
              "assets/photos/Gallary/My Exhibited Art Photographs/MEAT-01.JPG",
              "assets/photos/Gallary/My Exhibited Art Photographs/MEAT-02.JPG",
              "assets/photos/Gallary/My Exhibited Art Photographs/MEAT-03.JPG",
              "assets/photos/Gallary/My Exhibited Art Photographs/MEAT-04.JPG",
              "assets/photos/Gallary/My Exhibited Art Photographs/MEAT-05.JPG",
            ],
          },
        ],
      },
      {
        subFolder: "Rag Day Photographs",
        subSubFolders: [
          {
            subSubFolder: "Rag Day Photographs",
            files: [
              "assets/photos/Gallary/Rag Day Photographs/RDP-01.JPG",
              "assets/photos/Gallary/Rag Day Photographs/RDP-02.JPG",
              "assets/photos/Gallary/Rag Day Photographs/RDP-03.JPG",
              "assets/photos/Gallary/Rag Day Photographs/RDP-04.JPG",
              "assets/photos/Gallary/Rag Day Photographs/RDP-05.JPG",
              "assets/photos/Gallary/Rag Day Photographs/RDP-06.JPG",
              "assets/photos/Gallary/Rag Day Photographs/RDP-07.JPG",
              "assets/photos/Gallary/Rag Day Photographs/RDP-08.JPG",
            ],
          },
        ],
      },
    ],
  },
  {
    mainFolder: "Project Work Photographs",
    subFolders: [
      {
        subFolder: "Insect Pest Management Practices",
        subSubFolders: [
          {
            subSubFolder: "Insect Pest Management Practices",
            files: [
              "assets/photos/Project Work Photographs/Insect Pest Management Practices/Project-IPM-01.JPG",
              "assets/photos/Project Work Photographs/Insect Pest Management Practices/Project-IPM-02.JPG",
              "assets/photos/Project Work Photographs/Insect Pest Management Practices/Project-IPM-03.JPG",
              "assets/photos/Project Work Photographs/Insect Pest Management Practices/Project-IPM-04.JPG",
              "assets/photos/Project Work Photographs/Insect Pest Management Practices/Project-IPM-05.JPG",
              "assets/photos/Project Work Photographs/Insect Pest Management Practices/Project-IPM-06.JPG",
              "assets/photos/Project Work Photographs/Insect Pest Management Practices/Project-IPM-07.JPG",
              "assets/photos/Project Work Photographs/Insect Pest Management Practices/Project-IPM-08.JPG",
              "assets/photos/Project Work Photographs/Insect Pest Management Practices/Project-IPM-09.JPG",
              "assets/photos/Project Work Photographs/Insect Pest Management Practices/Project-IPM-10.JPG",
              "assets/photos/Project Work Photographs/Insect Pest Management Practices/Project-IPM-11.JPG",
            ],
          },
        ],
      },
      {
        subFolder: "Insect as a Food: Bangladesh Perspectives",
        subSubFolders: [
          {
            subSubFolder: "Edible Insect (Market, Collection, Consumption)",
            files: [
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Edible Insect (Market, Collection, Consumption)/EI-MCC-01.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Edible Insect (Market, Collection, Consumption)/EI-MCC-02.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Edible Insect (Market, Collection, Consumption)/EI-MCC-03.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Edible Insect (Market, Collection, Consumption)/EI-MCC-04.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Edible Insect (Market, Collection, Consumption)/EI-MCC-05.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Edible Insect (Market, Collection, Consumption)/EI-MCC-06.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Edible Insect (Market, Collection, Consumption)/EI-MCC-07.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Edible Insect (Market, Collection, Consumption)/EI-MCC-08.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Edible Insect (Market, Collection, Consumption)/EI-MCC-09.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Edible Insect (Market, Collection, Consumption)/EI-MCC-10.JPG",
            ],
          },
          {
            subSubFolder: "Survey-Chakma Photographs",
            files: [
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Chakma Photographs/S-CP-01.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Chakma Photographs/S-CP-02.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Chakma Photographs/S-CP-03.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Chakma Photographs/S-CP-04.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Chakma Photographs/S-CP-05.JPG",
            ],
          },
          {
            subSubFolder: "Survey-Garo Photographs",
            files: [
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Garo Photographs/S-GP-01.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Garo Photographs/S-GP-02.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Garo Photographs/S-GP-03.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Garo Photographs/S-GP-04.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Garo Photographs/S-GP-05.JPG",
            ],
          },
          {
            subSubFolder: "Survey-Marma Photographs",
            files: [
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Marma Photographs/S-Mar.P-01.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Marma Photographs/S-Mar.P-02.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Marma Photographs/S-Mar.P-03.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Marma Photographs/S-Mar.P-04.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Marma Photographs/S-Mar.P-05.JPG",
            ],
          },
          {
            subSubFolder: "Survey-Mro Photographs",
            files: [
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Mro Photographs/S-Mro.P-01.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Mro Photographs/S-Mro.P-02.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Mro Photographs/S-Mro.P-03.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Mro Photographs/S-Mro.P-04.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Mro Photographs/S-Mro.P-05.JPG",
            ],
          },
          {
            subSubFolder: "Survey-Tongchangya Photographs",
            files: [
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Tongchangya Photographs/S-Tong.P-01.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Tongchangya Photographs/S-Tong.P-02.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Tongchangya Photographs/S-Tong.P-03.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Tongchangya Photographs/S-Tong.P-04.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Tongchangya Photographs/S-Tong.P-05.JPG",
            ],
          },
          {
            subSubFolder: "Survey-Tripura Photographs",
            files: [
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Tripura Photographs/S-Trip.P-01.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Tripura Photographs/S-Trip.P-02.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Tripura Photographs/S-Trip.P-03.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Tripura Photographs/S-Trip.P-04.JPG",
              "assets/photos/Project Work Photographs/Insect as a Food: Bangladesh Perspectives/Survey-Tripura Photographs/S-Trip.P-05.JPG",
            ],
          },
        ],
      },
    ],
  },
];
